server:
  servlet:
    encoding:
      force-response: true
  port: 8082

spring:
  datasource:
    url: localhost
    username: root
    password: q1w2e3r4

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: create
